# Generated by Django 3.0.2 on 2020-01-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresidentialCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('google_campaign_id', models.CharField(max_length=100)),
                ('fec_id', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('presidential_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.PresidentialCampaign')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_ad_id', models.CharField(max_length=100)),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('number_of_days', models.IntegerField(default=0)),
                ('link', models.URLField(max_length=500)),
                ('ad_type', models.CharField(max_length=25)),
                ('spend_range', models.CharField(max_length=50)),
                ('impressions_range', models.CharField(max_length=50)),
                ('presidential_campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.PresidentialCampaign')),
            ],
        ),
    ]
